### ISSUE TITLE
soundcloud

### ISSUE THREAD

**Issue by Mkhaywe** [hangorazvan/yframe#1]
Hello , so i was wondering how do you make soundcloud work on this as after installing and adding models it doest show anything appreciate your help

**Comment by hangorazvan** [comment]
on the album or playlist click share button then embed and copy iframe code, something like this:

`<iframe width="100%" height="450" scrolling="no" frameborder="no" allow="autoplay" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/653929878&color=%23ff5500&auto_play=false&hide_related=false&show_comments=true&show_user=true&show_reposts=false&show_teaser=true"></iframe><div style="font-size: 10px; color: #cccccc;line-break: anywhere;word-break: normal;overflow: hidden;white-space: nowrap;text-overflow: ellipsis; font-family: Interstate,Lucida Grande,Lucida Sans Unicode,Lucida Sans,Garuda,Verdana,Tahoma,sans-serif;font-weight: 100;"><a href="https://soundcloud.com/razvanh" title="Răzvan Horia Cristea" target="_blank" style="color: #cccccc; text-decoration: none;">Răzvan Horia Cristea</a> · <a href="https://soundcloud.com/razvanh/sets/temple-of-love-extreme-audio-collection" title="Temple of Love - Broadcast Studio Mastered" target="_blank" style="color: #cccccc; text-decoration: none;">Temple of Love - Broadcast Studio Mastered</a></div>`

then put from this code on module config url: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/653929878"

see config instructions:
Soundcloud iframe mode example url: "https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/653929878"
Soundcloud playlist tracks must have embeded-player code active to be displayed publicly
